### PR TITLE
playgroundで閾値がどの程度から判定するのか表示する

### PR DESCRIPTION
**Pull request by R1013-T**
- https://github.com/TECH-C-LT/Peace-Net/issues/184

https://github.com/user-attachments/assets/2edc61ff-572b-47d1-8aa6-ecc421e98074

### CODE REVIEW

**Comment by naruse666** [comment]
`close: #184`のようにリンクするとPR mergeと共にissueも閉じれますよ
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by naruse666 — APPROVED** [review]
実装はやい

**Comment by R1013-T** [comment]
close: #184

**Review by waya279 — APPROVED** [review]
👏

**Pull request merged**
